#%RAML 1.0 DataType

displayName: File
description: A type to be used when a new file to be created.
uses:
  BaseTypes: ../libraries/base-types.raml
  Annotations: ../libraries/annotations.raml

properties:
  id:
    type: string
    description: The ID of the file.
  kind:
    (Annotations.readOnly):
    type: string
    description: |
      Identifies what kind of resource this is. Value: the fixed string "drive#file".
    enum: [drive#file]
    default: drive#file
    required: false
  name:
    type: string
    description: |
      The name of the file.

      This is not necessarily unique within a folder.
      Note that for immutable items such as the top level folders of shared drives, My Drive root folder, and Application Data folder the name is constant.
  mimeType:
    type: string
    required: false
    description: |
      The MIME type of the file.

      Google Drive will attempt to automatically detect an appropriate value from uploaded content if no value is provided. The value cannot be changed unless a new revision is uploaded.

      If a file is created with a Google Doc MIME type, the uploaded content will be imported if possible. The supported import formats are published in the About resource.
  description:
    type: string
    required: false
    description: |
      A short description of the file.
  starred:
    type: boolean
    required: false
    description: |
      Whether the user has starred the file.
  trashed:
    type: boolean
    required: false
    description: |
      Whether the file has been trashed, either explicitly or from a trashed parent folder.
      Only the owner may trash a file, and other users cannot see files in the owner's trash.
  explicitlyTrashed:
    (Annotations.readOnly):
    type: boolean
    required: false
    description: |
      Whether the file has been explicitly trashed, as opposed to recursively trashed from a parent folder.
  parents:
    type: string[]
    required: false
    description: |
      The IDs of the parent folders which contain the file.

      If not specified as part of a create request, the file will be placed directly in the user's My Drive folder.
      If not specified as part of a copy request, the file will inherit any discoverable parents of the source file.
      Update requests must use the addParents and removeParents parameters to modify the parents list.
  properties:
    type: object
    required: false
    description: |
      A collection of arbitrary key-value pairs which are visible to all apps.

      Entries with null values are cleared in update and copy requests.
  appProperties:
    type: object
    required: false
    description: |
      A collection of arbitrary key-value pairs which are private to the requesting app.

      Entries with null values are cleared in update and copy requests.
  spaces:
    (Annotations.readOnly):
    type: string[]
    required: false
    enum: [drive, appDataFolder, photos]
    description: |
      The list of spaces which contain the file. The currently supported values are 'drive', 'appDataFolder' and 'photos'.
  version:
    (Annotations.readOnly):
    type: number
    format: long
    description: |
      A monotonically increasing version number for the file. This reflects every change made to the file on the server, even those not visible to the user.
  webContentLink:
    (Annotations.readOnly):
    type: string
    description: |
      A link for downloading the content of the file in a browser. This is only available for files with binary content in Google Drive.
  webViewLink:
    (Annotations.readOnly):
    type: string
    description: |
      A link for opening the file in a relevant Google editor or viewer in a browser.
  iconLink:
    (Annotations.readOnly):
    type: string
    description: |
      A static, unauthenticated link to the file's icon.
  thumbnailLink:
    (Annotations.readOnly):
    type: string
    description: |
      A short-lived link to the file's thumbnail, if available.
      Typically lasts on the order of hours. Only populated when the requesting app can access the file's content.
  viewedByMe:
    (Annotations.readOnly):
    type: boolean
    description: |
      Whether the file has been viewed by this user.
  viewedByMeTime:
    type: datetime
    format: rfc3339
    description: |
      The last time the file was viewed by the user (RFC 3339 date-time).
  createdTime:
    type: datetime
    format: rfc3339
    description: |
      The time at which the file was created (RFC 3339 date-time).
  modifiedTime:
    type: datetime
    format: rfc3339
    description: |
      The last time the file was modified by anyone (RFC 3339 date-time).

      Note that setting modifiedTime will also update modifiedByMeTime for the user.
  modifiedByMeTime:
    (Annotations.readOnly):
    type: datetime
    format: rfc3339
    description: |
      The last time the file was modified by the user (RFC 3339 date-time).
  sharedWithMeTime:
    (Annotations.readOnly):
    type: datetime
    format: rfc3339
    description: |
      The time at which the file was shared with the user, if applicable (RFC 3339 date-time).
  sharingUser:
    (Annotations.readOnly):
    type: BaseTypes.User
    required: false
    description: |
      The user who shared the file with the requesting user, if applicable.
  owners:
    (Annotations.readOnly):
    type: BaseTypes.User[]
    required: false
    description: |
      The owners of the file. Currently, only certain legacy files may have more than one owner. Not populated for items in shared drives.
  lastModifyingUser:
    (Annotations.readOnly):
    type: BaseTypes.User
    required: false
    description: |
      The last user to modify the file.
  shared:
    (Annotations.readOnly):
    type: boolean
    required: false
    description: |
      Whether the file has been shared. Not populated for items in shared drives.
  ownedByMe:
    (Annotations.readOnly):
    type: boolean
    required: false
    description: |
      Whether the user owns the file. Not populated for items in shared drives.
  viewersCanCopyContent:
    (Annotations.readOnly):
    (Annotations.deprecated):
      Message: This property is deprecated.
      Hint: Use "copyRequiresWriterPermission" instead.
    type: boolean
    required: false
    description: |
      Whether the user owns the file. Not populated for items in shared drives.
  writersCanShare:
    type: boolean
    required: false
    description: |
      Whether users with only writer permission can modify the file's permissions.

      Not populated for items in shared drives.
  permissions:
    (Annotations.readOnly):
    type: array
    items: object
    required: false
    description: |
      The full list of permissions for the file.
      This is only available if the requesting user can share the file. Not populated for items in shared drives.
  folderColorRgb:
    type: string
    required: false
    description: |
      The color for a folder as an RGB hex string. The supported colors are published in the folderColorPalette field of the About resource.
      If an unsupported color is specified, the closest color in the palette will be used instead.
  originalFilename:
    type: string
    required: false
    description: |
      The original filename of the uploaded content if available, or else the original value of the name field.
      This is only available for files with binary content in Google Drive.
  fullFileExtension:
    (Annotations.readOnly):
    type: string
    required: false
    description: |
      The full file extension extracted from the name field. May contain multiple concatenated extensions, such as "tar.gz". This is only available for files with binary content in Google Drive.

      This is automatically updated when the name field changes, however it is not cleared if the new name does not contain a valid extension.
  fileExtension:
    (Annotations.readOnly):
    type: string
    required: false
    description: |
      The final component of fullFileExtension. This is only available for files with binary content in Google Drive.
  md5Checksum:
    (Annotations.readOnly):
    type: string
    required: false
    description: |
      The MD5 checksum for the content of the file. This is only applicable to files with binary content in Google Drive.
  size:
    (Annotations.readOnly):
    type: number
    format: long
    required: false
    description: |
      The size of the file's content in bytes. This is only applicable to files with binary content in Google Drive.
  quotaBytesUsed:
    (Annotations.readOnly):
    type: number
    format: long
    required: false
    description: |
      The number of storage quota bytes used by the file. This includes the head revision as well as previous revisions with keepForever enabled.
  headRevisionId:
    (Annotations.readOnly):
    type: string
    required: false
    description: |
      The ID of the file's head revision. This is currently only available for files with binary content in Google Drive.
  contentHints:
    (Annotations.readOnly):
    type: !include content-hints.raml
  imageMediaMetadata:
    (Annotations.readOnly):
    type: !include image-media-metadata.raml
  videoMediaMetadata:
    (Annotations.readOnly):
    type: !include video-media-metadata.raml
  capabilities:
    (Annotations.readOnly):
    type: !include capabilities.raml
  isAppAuthorized:
    (Annotations.readOnly):
    type: boolean
    required: false
    description: |
      Whether the file was created or opened by the requesting app.
  hasThumbnail:
    (Annotations.readOnly):
    type: boolean
    required: false
    description: |
      Whether this file has a thumbnail. This does not indicate whether the requesting app has access to the thumbnail.
      To check access, look for the presence of the thumbnailLink field.
  thumbnailVersion:
    (Annotations.readOnly):
    type: number
    format: long
    required: false
    description: |
      The thumbnail version for use in thumbnail cache invalidation.
  modifiedByMe:
    (Annotations.readOnly):
    type: boolean
    required: false
    description: |
      Whether the file has been modified by this user.
  trashingUser:
    (Annotations.readOnly):
    type: BaseTypes.User
    required: false
    description: |
      If the file has been explicitly trashed, the user who trashed it. Only populated for items in shared drives.
  trashedTime:
    (Annotations.readOnly):
    type: datetime
    format: rfc3339
    description: |
      The time that the item was trashed (RFC 3339 date-time). Only populated for items in shared drives.
  teamDriveId:
    (Annotations.readOnly):
    (Annotations.deprecated):
      Message: This property is deprecated.
      Hint: Use "driveId" instead.
    type: string
    description: |
      The time that the item was trashed (RFC 3339 date-time). Only populated for items in shared drives.
  driveId:
    (Annotations.readOnly):
    type: string
    description: |
      ID of the shared drive the file resides in. Only populated for items in shared drives.
  hasAugmentedPermissions:
    (Annotations.readOnly):
    type: boolean
    description: |
      Whether there are permissions directly on this file. This field is only populated for items in shared drives.
  permissionIds:
    (Annotations.readOnly):
    type: string[]
    description: |
      List of permission IDs for users with access to this file.
  copyRequiresWriterPermission:
    type: boolean
    description: |
      Whether the options to copy, print, or download this file, should be disabled for readers and commenters.
  exportLinks:
    (Annotations.readOnly):
    type: object
    required: false
    description: |
      Links for exporting Google Docs to specific formats.
